openapi: 3.0.1
info:
  title: Rory Retro Google Docs Plugin
  version: 1.0.0
paths:
  /create-doc:
    post:
      operationId: createGoogleDoc
      summary: Maak een Google Document aan
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                content:
                  type: string
              required:
                - title
                - content
      responses:
        '200':
          description: Succesvol aangemaakt
          content:
            application/json:
              schema:
                type: object
                properties:
                  documentId:
                    type: string
                  documentUrl:
                    type: string
